# deployment/docker-compose/redis.yml
version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis-server
    restart: unless-stopped

    # Komut satırı konfigürasyonu
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru --requirepass redis123

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_PASSWORD=redis123

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

    # Health check
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Redis Commander - Web UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped

    ports:
      - "8081:8081"

    environment:
      - REDIS_HOSTS=local:redis-server:6379
      - REDIS_PASSWORD=redis123

    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
